### ISSUE TITLE
Could not pass event EntityCombustByEntityEvent

### ISSUE THREAD

**Issue by Zelda-devs** [Euphillya/WorldGuard-Folia#1]
https://mclo.gs/8FDFWgA

**Comment by Euphillya** [comment]
[worldguard-bukkit-7.0.13-SNAPSHOT-dist.zip](https://github.com/user-attachments/files/17071904/worldguard-bukkit-7.0.13-SNAPSHOT-dist.zip)
Can you try ?

**Comment by Zelda-devs** [comment]
> [worldguard-bukkit-7.0.13-SNAPSHOT-dist.zip](https://github.com/user-attachments/files/17071904/worldguard-bukkit-7.0.13-SNAPSHOT-dist.zip) Can you try ?

I activated this on my server rn, I'll check the logs today and let you know how it goes.

**Comment by Euphillya** [comment]
> > [worldguard-bukkit-7.0.13-SNAPSHOT-dist.zip](https://github.com/user-attachments/files/17071904/worldguard-bukkit-7.0.13-SNAPSHOT-dist.zip) Can you try ?
> 
> I activated this on my server rn, I'll check the logs today and let you know how it goes.

Thanks, don't hesitate if another bug comes

**Comment by Zelda-devs** [comment]
> > > [worldguard-bukkit-7.0.13-SNAPSHOT-dist.zip](https://github.com/user-attachments/files/17071904/worldguard-bukkit-7.0.13-SNAPSHOT-dist.zip) Can you try ?
> > 
> > 
> > I activated this on my server rn, I'll check the logs today and let you know how it goes.
> 
> Thanks, don't hesitate if another bug comes

Hey
https://mclo.gs/C1UU9vN
I am using the Zelteams plugin and I see its name in the bottom lines of the worldguard error. I am not sure if this is caused by worldguard or the zelteams plugin I am using.

**Comment by Euphillya** [comment]
> Hey
> https://mclo.gs/C1UU9vN
> I am using the Zelteams plugin and I see its name in the bottom lines of the worldguard error. I am not sure if this is caused by worldguard or the zelteams plugin I am using.

It must come from the other plugin, because it tries to open an inventory asynchronously, so WorldGuard wants to check if it has the right. And since it opens badly, it creates an error.

At least that's my opinion.

**Comment by Zelda-devs** [comment]
https://mclo.gs/BMDGpSR
What about this?

**Comment by Euphillya** [comment]
@Zelda-devs try this build : https://github.com/Euphillya/WorldGuard-Folia/actions/runs/11079016124
