### ISSUE TITLE
WorldGuard Folia 1.21.1 SPAM ERROR IN CONSOLE FATAL ERROR

### ISSUE THREAD

**Issue by kitovoi111** [Euphillya/WorldGuard-Folia#4]
WorldGuard Folia 1.21.1 SPAM ERROR IN CONSOLE FATAL ERROR

[latest.log](https://github.com/user-attachments/files/17978004/latest.log)

**Comment by kitovoi111** [comment]
I can place any blocks in other's region. WorldGuard broken.

**Comment by kitovoi111** [comment]
This server is running Folia version 1.21.1-DEV-dev/1.21.1@2e7bc07 (2024-11-18T16:35:46Z) (Implementing API version 1.21.1-R0.1-SNAPSHOT)
You are running the latest version

**Comment by kitovoi111** [comment]
worldguard-bukkit-7.0.13-SNAPSHOT-dist.jar
worldedit-bukkit-7.3.9-SNAPSHOT-dist.jar

**Comment by kitovoi111** [comment]
i use your latest fixed version. my WorldGuard full broken :C

**Comment by Euphillya** [comment]
Stop spamming

**Comment by Euphillya** [comment]
This is a WorldGuard bug, not a bug from my side.

**Comment by Euphillya** [comment]
try this version = https://github.com/Euphillya/WorldGuard-Folia/actions/runs/11645662324

**Comment by kitovoi111** [comment]
> try this version = https://github.com/Euphillya/WorldGuard-Folia/actions/runs/11645662324

this version working good. and have this error https://github.com/Euphillya/WorldGuard-Folia/issues/3

**Comment by Euphillya** [comment]
I see, but you can ignore
